output:
  logstash:
    enabled: true
    hosts:
      - 172.17.9.15:5044
    timeout: 15

filebeat:
  prospectors:
    -
      paths:
        - /app/logs/all-logs.log
      json.overwrite_keys: true
      json.keys_under_root: true
      json.message_key: "@message"
      fields_under_root: true
      tags: [
        "i",
        "heart",
        "json"
      ]
